# Generated by Django 5.1.2 on 2024-11-03 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_alter_user_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Snippet',
        ),
        migrations.AlterModelOptions(
            name='snippet',
            options={'ordering': ['created']},
        ),
    ]
