# Generated by Django 5.1.2 on 2024-11-03 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_rename_user_snippet_alter_snippet_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
