# Generated by Django 5.1.2 on 2024-11-03 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_alter_snippet_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Snippet',
            new_name='Info',
        ),
    ]
