# Generated by Django 5.1.2 on 2024-11-06 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_rename_snippet_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=6),
        ),
    ]
